[colors]
[colors.primary]
background = "0x061A2B"
foreground = "0xE8E5D8"

[colors.normal]
black = "0x0A3152"
red = "0xF47770"
green = "0x45D3C2"
yellow = "0xF6D45A"
blue = "0x087FA3"
magenta = "0xFFAA63"
cyan = "0x00B8C8"
white = "0xD5E5DF"

[colors.bright]
black = "0x34566A"
red = "0xFF8B7E"
green = "0x72E5CF"
yellow = "0xFFE47A"
blue = "0x45B8D0"
magenta = "0xFFC17A"
cyan = "0x45E6DD"
white = "0xF7E8CC"
