# Theme: sunset-osaka

# Main bg
theme[main_bg]="#061a2b"

# Main text color
theme[main_fg]="#6f858b"

# Title color for boxes
theme[title]="#f7e8cc"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#00b8c8"

# Background color of selected item in processes box
theme[selected_bg]="#0a3152"

# Foreground color of selected item in processes box
theme[selected_fg]="#d5e5df"

# Color of inactive/disabled text
theme[inactive_fg]="#4d6874"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#45d3c2"

# Cpu box outline color
theme[cpu_box]="#6f858b"

# Memory/disks box outline color
theme[mem_box]="#6f858b"

# Net up/down box outline color
theme[net_box]="#6f858b"

# Processes box outline color
theme[proc_box]="#6f858b"

# Box divider line and small boxes line color
theme[div_line]="#4d6874"

# Temperature graph colors
theme[temp_start]="#45d3c2"
theme[temp_mid]="#f6d45a"
theme[temp_end]="#f47770"

# CPU graph colors
theme[cpu_start]="#087fa3"
theme[cpu_mid]="#00b8c8"
theme[cpu_end]="#45d3c2"

# Mem/Disk free meter
theme[free_start]="#0a3152"
theme[free_mid]="#087fa3"
theme[free_end]="#45d3c2"

# Mem/Disk cached meter
theme[cached_start]="#f6d45a"
theme[cached_mid]="#ffaa63"
theme[cached_end]="#f47770"

# Mem/Disk available meter
theme[available_start]="#087fa3"
theme[available_mid]="#00b8c8"
theme[available_end]="#45d3c2"

# Mem/Disk used meter
theme[used_start]="#d96c5f"
theme[used_mid]="#f47770"
theme[used_end]="#ffaa63"

# Download graph colors
theme[download_start]="#087fa3"
theme[download_mid]="#00b8c8"
theme[download_end]="#45d3c2"

# Upload graph colors
theme[upload_start]="#d96c5f"
theme[upload_mid]="#ffaa63"
theme[upload_end]="#f6d45a"
