source ~/.local/share/calos/bash/rc

# set up fzf key bindings and fuzzy completion

eval "$(fzf --bash)"

# yazi key functionality improvement

function y() {
  local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
  yazi "$@" --cwd-file="$tmp"
  IFS= read -r -d '' cwd <"$tmp"
  [ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
  rm -f -- "$tmp"
}

# terminal upgrades

bind 'set show-all-if-ambiguous on'
bind 'TAB:menu-complete'
mkcd() { mkdir "$1" && cd "$1"; }

# aliases

alias oops='sudo $(history -p !!)'
alias grep='grep --color=auto'
alias please='sudo'
alias cat='bat --style grid,header,header-filename,header-filesize '
alias svim='sudoedit '
alias showoff='clear && fastfetch && echo $'\n' && fortune'

# first terminal boot service

if ! systemctl is-active --quiet bootmsg; then
#  echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
  clear
#  pamixer --set-volume 80
  sudo systemctl start bootmsg.service
  clear
  fastfetch
  hyprctl -q hyprsunset temperature 6600
fi

# starship config

export STARSHIP_CONFIG=~/.config/starship.toml
