[[mgr.prepend_keymap]]
on = "n"
run = "create"
[[mgr.prepend_keymap]]
on  = "<C-h>"
run = "hidden toggle"
[[mgr.prepend_keymap]]
on  = "o"
run = "open --interactive"
[[mgr.prepend_keymap]]
desc = "Start bunny.yazi"
on = ";"
run = "plugin bunny"

# Optionally, add another keymap to immediately fuzzy search bookmarks
[[mgr.prepend_keymap]]
desc = "Start bunny.yazi fuzzy search"
on = "'"
run = "plugin bunny fuzzy"
