# yazi.toml
[mgr]
show_hidden = true

[opener]

wallpaper = [
{ run = 'awww img %s --resize stretch --transition-type random --transition-fps 144 --transition-duration 1; ln -nsf %s $HOME/.config/calos/current/background; sleep 0.2; cp %s ~/Pictures/Wallpapers/', desc = "Set and Add as Wallpaper" }
]

imageedit = [
{ run = 'pinta %s', desc = "Pinta Image Editor" }
]

image = [
{ run = 'pqiv -i --scale-mode-screen-fraction=0.33 %s', desc = "Pqiv Image Viewer" },
]

text = [
	{ run = 'nvim %s', block = true, desc = "Neovim Text Editor"},
]
 
glow = [
	{ run = 'glow -t %s', block = true, desc = "Glow Markdown Viewer"},
]

extract = [
 {  run = '7z x %s -o*',  desc = "Extract with 7zip" }
]

extracttar = [
{ run = 'tar -xf %s', desc = "Extrar .tar.xz file" }
]

execute = [
    { run = '%s', block = true, desc = "Execute as shell command"},
]

music = [
{ run = 'ffplay -nodisp -autoexit %s' },
]

video = [
{ run = 'ffplay %s' },
]

imageclip = [
{ run = 'wl-copy --type image/png < %s', desc = "Copy Image to Clipboard" },
]

[open]

rules = [

{ url = "*.{zip,rar,7z}", use = "extract" },

{ url = "*.gif", use = ["image", "imageclip"] },

{ url = "*.{jpg,png}", use = ["image", "imageedit", "wallpaper", "imageclip"] },

{ url = "*.{conf,toml,txt,ini,jsonc,yml,json,lua,css,js,bash*}", use = "text" },

{ url = "*.{mp3,wav,ogg}", use = "music" },

{ url = "*.{mkv,mp4}", use = "video" },

{ url = "*.md", use = ["glow", "text"] },

{ url = "*.sh", use = ["text", "execute"] },

{ url = "*.{tar.xz,tar.gz}", use = "extracttar" },

{ url = "*", use = ["text", "execute"] },

]

[[plugin.prepend_previewers]]
url = "*/"
run = "eza-preview"

[[plugin.prepend_previewers]]
url = "*.md"
run = 'faster-piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dracula -- "$1"'

[[plugin.prepend_previewers]]
url = "*{png,jpg,jpeg}"
run = 'faster-piper -- viu -b -w 50 -h 25 -- "$1"'

[[plugin.prepend_previewers]]
url = "*{webp,gif}"
run = 'faster-piper -- identify -format "Format: %m\nDimensions: %wx%h\nDepth: %z-bit\nColorspace: %[colorspace]\nFilesize: %b\n" -- "$1"'
